spring:
  application:
    name: config-server
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yany8060/yany-spring-cloud.git  # 配置git仓库的地址
          username: XXXX                                        # git仓库的账号
          password: XXXX                                        # git仓库的密码
          search-paths: config-center                             # git仓库地址下的相对地址，可以配置多个，用,分割。
#          basedir: config-center/config-repo
        native:
          search-locations: /tmp/config-center


# http://localhost:7010/yany-test.yml
# http://localhost:7010/yany-test.json

---
server:
  port: 7010

# 实现高可用 可启动多个服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1081/eureka/